### ISSUE TITLE
As a developer I want to implement sqlite3 for our web API to read and store cheeps with.

### ISSUE THREAD

**Issue by YeChengde** [ITU-BDSA2024-GROUP5/Chirp#29]
Implement DBFacade.cs to read cheeps from sqlite3 database so chirp shows cheeps from sqlite3 database and not hardcoded messages.

Success criteria:
Chirp website shows messages in sqlite3 db.

**Comment by MarkusStaael** [comment]
Suggested title: As a developer I want to implement sqlite3 for our web API to read and store cheeps with.
