### ISSUE TITLE
As a Developer I want to have the length of a given users cheep constrained by that limiting the possible amount of data to get stored into the database at once.

### ISSUE THREAD

**Issue by MessiGames30** [ITU-BDSA2024-GROUP5/Chirp#62]
In order for our database to not be flooded by long messages we have to limit the amount of character that a cheep can contain. We will place that cap at 160 characters.

Success criteria: 
Testing that cheeps longer that 160 characters are not written into the database. That is at least the need to have for integration. 

Further features such as making the user aware of the cheep being to long would be a nice to have.

**Comment by sarazj** [comment]
Feature that makes the user aware their message is too long has yet to be implemented, although the rest has been done.
